name: WakaTime Coding Metrics

on:
  schedule:
    # Запуск каждые 12 часов (можно настроить под себя)
    - cron: '0 */12 * * *'
  # Позволяет запускать обновление вручную кнопкой в GitHub Actions
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          # Настройки внешнего вида (выберите true/false)
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
          SHOW_TOTAL: true
